### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by SpongyBacon** [Fireflies/quotes#1]
[00:37:01] Ƴαяиσ (Єνσℓтя): [00:32] Connor Harries: 

<<< https://github.com/Fireflies/quotesI expected a repo with interesting quotes from Connor
[00:37:10] Ƴαяиσ (Єνσℓтя): You dissapoint me
[00:37:12] Ƴαяиσ (Єνσℓтя): F*** GRAMMAR

**Comment by Evoltr** [comment]
yesyes am want quotes from connor

**Comment by Fireflies** [comment]
You can make your own with this tool. :)

**Comment by Evoltr** [comment]
NO DUN CLOSE YOU DID NOT FIX

**Comment by SpongyBacon** [comment]
owowujusrekyarno

**Comment by Fireflies** [comment]
I did fix it though :)

**Comment by SpongyBacon** [comment]
but cpu still am kil
